/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
  // on Android, a nasty hack is needed: {"resizeClear": true}
$("li a").each(function(){
  var a = $(this) ; 
  var cityName = $(this).text() ;
  $.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+cityName+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
    var currentTemperature = FtoC(data.query.results.channel.item.condition.temp) ;
    a.text(a.text()+currentTemperature+"℃")
  })
})


$('#dropdown li').on('click', function(){
//    alert($(this).text());
  var cityName = $(this).text() ;
      $("#displayedRegion").text(cityName) ;
  $.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22"+cityName+"%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",function(data){
      console.log (data) ; // 可以比較方便你找到你要的資料在這個物件的哪個位置
      // 例如
      var currentTemperature = FtoC(data.query.results.channel.item.condition.temp) ; // 就可以找到現在溫度
      var currentDate = data.query.results.channel.item.pubDate ;
      var currentDescription = data.query.results.channel.item.condition.text ;
      $(".date").text(currentDate) ;
      $(".conditionText").text(currentDescription) ;
      $(".temperature").text(currentTemperature) ;

      var forecastDate1 = data.query.results.channel.item.forecast[1].date ;
      var forecastDate2 = data.query.results.channel.item.forecast[2].date ;
      var forecastDate3 = data.query.results.channel.item.forecast[3].date ;
      $("#forcastDate1").text(forecastDate1) ;
      $("#forcastDate2").text(forecastDate2) ;
      $("#forcastDate3").text(forecastDate3) ;

      var forecastDescription1 = data.query.results.channel.item.forecast[1].text ;
      var forecastDescription2 = data.query.results.channel.item.forecast[2].text ;
      var forecastDescription3 = data.query.results.channel.item.forecast[3].text ;
      $("#forcastDescription1").text(forecastDescription1) ;
      $("#forcastDescription2").text(forecastDescription2) ;
      $("#forcastDescription3").text(forecastDescription3) ;

      var forcastTemparature11 = FtoC(data.query.results.channel.item.forecast[1].low) ;
      var forcastTemparature12 = FtoC(data.query.results.channel.item.forecast[1].high) ;
      var forcastTemparature21 = FtoC(data.query.results.channel.item.forecast[2].low) ;
      var forcastTemparature22 = FtoC(data.query.results.channel.item.forecast[2].high) ;
      var forcastTemparature31 = FtoC(data.query.results.channel.item.forecast[3].low) ;
      var forcastTemparature32 = FtoC(data.query.results.channel.item.forecast[3].high) ;
      $("#forcastTemparature1").text(forcastTemparature11+"-"+forcastTemparature12+"℃" ) ;
      $("#forcastTemparature2").text(forcastTemparature21+"-"+forcastTemparature22+"℃" ) ;
      $("#forcastTemparature3").text(forcastTemparature31+"-"+forcastTemparature32+"℃" ) ;

      var currentCode = data.query.results.channel.item.condition.code ;
      var forecastCode1 = data.query.results.channel.item.forecast[1].code ;
      var forecastCode2 = data.query.results.channel.item.forecast[2].code ;
      var forecastCode3 = data.query.results.channel.item.forecast[3].code ;
      var getSkyconSetting0 = getSkyconSetting(parseInt(currentCode)) ;
      var getSkyconSetting1 = getSkyconSetting(parseInt(forecastCode1)) ;
      var getSkyconSetting2 = getSkyconSetting(parseInt(forecastCode2)) ;
      var getSkyconSetting3 = getSkyconSetting(parseInt(forecastCode3)) ;
      skycons.add("today",getSkyconSetting0) ;
      skycons.add("forcastDescription1",getSkyconSetting1) ;
      skycons.add("forcastDescription2",getSkyconSetting2) ;
      skycons.add("forcastDescription3",getSkyconSetting3) ;
      skycons.play();
      console.log("getSkyconSetting1",forecastCode1);
      console.log("getSkyconSetting2",forecastCode2);
      console.log("getSkyconSetting3",forecastCode3);
  })
});

$("#TaipeiCity").trigger('click')

function getSkyconSetting(weatherCode){
  switch(weatherCode){
    case 0: case 1: case 2: case 3: case 4: case 8: case 9: case 10: case 11: case 12: case 37: case 38: case 39: case 40: case 45: case 47:
      return Skycons.RAIN ;
      break ;
    case 5: case 13: case 14: case 15: case 16: case 41: case 42: case 43: case 44: case 46:  
      return Skycons.SNOW ;
      break ;
    case 6: case 7: case 17: case 18: case 35:
      return Skycons.SLEET ;
      break ; 
    case 19: case 20: case 21: case 22: 
      return Skycons.FOG ;
      break ;
    case 23: case 24: case 25: 
      return Skycons.WIND ;
      break ;
    case 26: case 27: case 28:
      return Skycons.CLOUDY ;
      break ; 
    case 29: case 30: 
      return Skycons.PARTLY_CLOUDY_DAY ;
      break ;
    case 31: case 32: case 33: case 34: case 36:
      return Skycons.CLEAR_DAY ;
      break ;
    default :
      return Skycons.PARTLY_CLOUDY_DAY ;
      break ;
  }
}

function FtoC(f){
  return Math.round((f-30)*5/9) ;
}